[package]
name = "ez-chess"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
ggez = { version = "0.9.3", default-features = false }
rand = "0.8.5"
